services:
  main:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["sh", "-c", "sleep infinity"]
    depends_on: [target]
  target:
    build:
      context: ./assets/target
    command: ["python3", "/srv/server.py"]
    expose: ["8101"]
